version: '3.9'

networks:
  huihui-mahjong:
    driver: bridge
services:
  frontend:
    depends_on:
      - backend
    image: hp4129889/huihui-mahjong:frontend
    container_name: huihui-mahjong-frontend
    restart: always
    environment:
      - REACT_APP_HUIHUI_MAHJONG_API_BASE_URL=http://backend:8000/
    ports:
      - "3030:3030"
    networks:
      - huihui-mahjong

  backend:
    depends_on:
      - postgres
    image: hp4129889/huihui-mahjong:backend
    container_name: huihui-mahjong-backend
    restart: always
    environment:
      - APP_PORT=8000
      - HUIHUI_POSTGRES_USER=huihui
      - HUIHUI_POSTGRES_PASSWORD=huihui
      - HUIHUI_POSTGRES_DB=huihui-mahjong
      - HUIHUI_POSTGRES_HOST=postgres
      - HUIHUI_POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - huihui-mahjong
  postgres:
    image: postgres:latest
    container_name: huihui-mahjong-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: huihui
      POSTGRES_PASSWORD: huihui
      POSTGRES_DB: huihui-mahjong
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - huihui-mahjong
