version: '3.9'

networks:
  huihui-mahjong:
    driver: bridge

services:
  nginx:
    depends_on:
      - frontend
      - backend
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - huihui-mahjong

  frontend:
    depends_on:
      - backend
    image: hp4129889/huihui-mahjong:frontend
    container_name: frontend
    restart: always
    ports:
      - "3030:3030"
    networks:
      - huihui-mahjong

  backend:
    depends_on:
      - postgres
    image: hp4129889/huihui-mahjong:backend
    container_name: backend
    command: sh -c "npm run migration:run && npm start"
    restart: always
    environment:
      - APP_PORT=8000
      - APP_API_PREFIX=/mahjong/api
      - HUIHUI_POSTGRES_USER=huihui
      - HUIHUI_POSTGRES_PASSWORD=huihui
      - HUIHUI_POSTGRES_DB=huihui-mahjong
      - HUIHUI_POSTGRES_HOST=postgres
      - HUIHUI_POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - huihui-mahjong

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: huihui
      POSTGRES_PASSWORD: huihui
      POSTGRES_DB: huihui-mahjong
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - huihui-mahjong

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hp4129889@gmail.com
      PGADMIN_DEFAULT_PASSWORD: huihui
    ports:
      - "8081:80"
    networks:
      - huihui-mahjong
