version: '3.9'

networks:
  huihui-mahjong:
    driver: bridge

volumes:
  db-data:


services:
  nginx:
    image: nginx:latest
    container_name: huihui-mahjong-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - huihui-mahjong

  frontend:
    depends_on:
      - backend
    image: hp4129889/huihui-mahjong:frontend
    container_name: huihui-mahjong-frontend
    restart: always
    networks:
      - huihui-mahjong

  backend:
    depends_on:
      - postgres
    image: hp4129889/huihui-mahjong:backend
    container_name: huihui-mahjong-backend
    restart: always
    networks:
      - huihui-mahjong

  postgres:
    image: postgres:latest
    container_name: huihui-mahjong-postgres
    restart: always
    ports:
      - "${HUIHUI_POSTGRES_PORT}:${HUIHUI_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${HUIHUI_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HUIHUI_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HUIHUI_POSTGRES_DB}
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    networks:
      - huihui-mahjong
